name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev libvips curl ffmpeg

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Configure DB
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/wip"
        run: bin/rails db:setup

      - name: Lint code for consistent style
        run: bin/check-code-style

      - name: Scan code for security vulnerabilities
        run: bin/check-vulnerable-code

      - name: Check vulnerable gems
        run: bin/check-vulnerable-gems

      - name: Run Tests
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/wip"
        run: bin/rails test:all
